Added Nimbus Testing
ma499/Nimbus pull request #9
Opened 2018-05-22 11:22 UTC by sedainterxion

- Created Nimbus.Testing library to abstract boilerplate for setting up a unit test on a message handler.
- Created unit tests for Nimbus.Testing

2018-05-22 13:17 UTC, ma499 requested changes
Looks good - just think we should make the assembly attributes consistent with the other projects.

2018-05-22 13:17 UTC, ma499 commented on src/Nimbus.Testing/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2018")]
Can you get the above filled out to be consistent with the other projects? Will help with acceptance of pull request to upstream.

2018-05-22 13:24 UTC, ma499 commented on src/Nimbus.Testing/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2018")]
It is consistent. Whoops!

2018-05-22 13:24 UTC, ma499 approved these changes

2018-05-23 11:04 UTC, GiampaLab approved these changes

2018-05-23 15:43 UTC, rickyattiliaaq approved these changes

2018-05-25 10:35 UTC, merged